version: '3.9'

services:
    api:
      build: ./api
      ports:
        - "5000:5000"
      volumes:
        - './api/Database:/api/Database'
        - './api/Logs:/api/Logs'
    cert-checker:
      build: ./cert-checker
      ports:
        - "5001:5001"
      volumes:
        - './cert-checker/logs:/cert-checker/logs'
    frontend:
      build: ./frontend
      ports:
        - "8080:80"